### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by askhat** [zmagyar/extjs-loader#1]
Sorry for dropping it on you, I don't even know where to start to dig

Full output
```
Unhandled rejection TypeError: Cannot read property 'query' of undefined
    at Promise.each.then (/Users/askhat/code/polycode-frontend/node_modules/extjs-loader/lib/loader.js:164:26)
    at tryCatcher (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/askhat/code/polycode-frontend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

Mentioned block
`loader.js:162`
```javascript
.then(() => {
  let ExtParser = pathMap['Ext'];
  if (ExtParser.query) {
    let fileProps = ExtParser.fileMapCache[self.resourcePath];
    if (fileProps && fileProps.requires && fileProps.requires.length > 0) {
      let requireStr = '';
      fileProps.requires.forEach((require) => {
        let result = ExtParser.query(require);
        if (result instanceof Array) {
          result.forEach((require) => {
            requireStr += `require('${require.src}');`
          });
        } else {
          requireStr += `require('${ExtParser.query(require).src}');`
        }
      })
      updates.push({type: 'add', start: 0, end: 0, data: requireStr});
    }
  }
}
```

`webpack.config.js`
```javascript
module.exports = {
  devtool: 'inline-source-map',
  entry: {
    ext: path.join(__dirname, 'ext/build/ext-all'),
    app: path.join(__dirname, 'app.js')
  },
  output: {
    path: path.join(__dirname, 'dst'),
    filename: 'bundle.js'
  },
  devServer: {
    contentBase: 'dst'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'extjs-loader'
      }
    ]
  }
}
```

**Comment by zmagyar** [comment]
Most likely you do not have the module's peer dependency ([ext-parser](https://www.npmjs.com/package/extjs-parser)) installed.

**Comment by askhat** [comment]
But I have `ext-parser` installed, version `^1.0.4`

**Comment by zmagyar** [comment]
Ah, sorry. Seeing the above webpack config file, it looks like you are missing some essential config parameters. E.g. you do not have the paths configured. See https://github.com/zmagyar/extjs-loader#via-webpack-config-recommended for example.

**Comment by askhat** [comment]
Could you also give a minimal necessary example of configuration?

**Comment by askhat** [comment]
So, I added following config block

```javascript
options: {
  debug: true,
  namespace: 'Poly',
  paths: {
    'Deft': false,
    'Ext': new extParser({
      toolkit: 'classic',
      path: path.join(__dirname, 'ext')
  })
}
```

And now error is

```
Unhandled rejection TypeError: Cannot read property '/Users/askhat/code/polycode-frontend/node_modules/webpack-dev-server/client/index.js' of undefined
```

And again, I don't quite understand what is happening. Perhaps due to lack either webpack and ext knowledge. Could you point me towards correct direction and explain things, please.

**Comment by zmagyar** [comment]
Will post a sample project soon.

**Comment by zmagyar** [comment]
Hi @askhat,

Sorry for the delay, it's been a busy period here. But finally managed to find some time to come up with an example to demonstrate the usage of the loader. You can find this sample project at https://github.com/zmagyar/extjs-loader-sample.

**Comment by zmagyar** [comment]
Description has been updated to include cross link to the sample project at eae7bbb1f56f7d5cdeac5359f44e68ca3af30c1f
